version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - react-app
      - grafana
    networks:
      - grafana-net

  react-app:
    build: ../frontend
    networks:
      - grafana-net

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_ROOT_URL=http://localhost:8081/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_PANELS_DISABLE_SANITIZE_HTML=true   
    networks:
      - grafana-net
    # ports:
    # # For testing inside container. do not public
    #   - "3000:3000" 
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana-data:
